media:
  input: src/assets
  output: ../../assets
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    view:
      fields: [ title, date, published ] # title is the first entry and thus will be set to primary
    fields:
      - name: author
        label: Author
        type: string
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: pubDate
        label: pubDate
        type: date
        options:
          format: yyyy-MM-dd