nav:
  - label: 🚀 Publish Site
    url: https://github.com/hassan-anees/hassananees/actions/workflows/deploy-cloudflare.yml
    
media:
  - name: images
    label: Images
    input: src/assets
    output: ../../assets
  - name: documents
    label: Documents
    input: public/documents
    output: ../../../public/documents
  - name: covers
    label: Covers
    input: public/covers
    output: ../../../public/covers
content:
  - name: work
    label: Work
    type: file
    path: src/data/work.json
    fields:
      - name: industry
        label: Industry
        type: list
        fields:
          - { name: title, label: Title, type: string }
          - { name: organization, label: Organization, type: string }
          - { name: period, label: Period, type: string }
      - name: research
        label: Research
        type: list
        fields:
          - { name: title, label: Title, type: string }
          - { name: organization, label: Organization, type: string }
          - { name: period, label: Period, type: string }

  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: '{primary}.md'
    view:
      fields: [ cover, title, body, date, published, pubDate, draft ] # title is the first entry and thus will be set to primary
    fields:
      - name: author
        label: Author
        type: string
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: pubDate
        label: Publish Date
        type: date
        options:
          format: yyyy-MM-dd
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: cover
        label: Cover Image
        type: image
        options:
          multiple: false
          media: covers
      - name: attachments
        label: Attachments
        type: file
        options:
          multiple: true
          media: documents
      - name: body
        label: Body
        type: rich-text
    
