media:
  - name: images
    label: Images
    input: src/assets
    output: ../../assets
  - name: documents
    label: Documents
    input: public/documents
    output: ../../../public/documents
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    view:
      fields: [ cover, title, body, date, published, pubDate,  ] # title is the first entry and thus will be set to primary
    fields:
      - name: author
        label: Author
        type: string
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: pubDate
        label: Publish Date
        type: date
        options:
          format: yyyy-MM-dd
      - name: cover
        label: Cover Image
        type: file
        options:
          multiple: false
          media: images
      - name: attachments
        label: Attachments
        type: file
        options:
          multiple: true
          media: documents
      - name: body
        label: Body
        type: rich-text
    