media:
  input: src/assets
  output: assets
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    view:
      fields: [ title, date, published ] # title is the first entry and thus will be set to primary
    fields:
      - name: title
        label: Title
        type: string